apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHk4OS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiWTJocGNuVTZRMmhwY25WQU9UTTVNems9IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson